kind: pipeline
name: default
clone:
  depth: 1
trigger:
  event:
  - push
steps:
- name: docker build
  image: plugins/docker
  privileged: true
  settings:
    repo: registry.sherpany.com/talk-relay
    tags: dev
    build_args:
    - source_version=${DRONE_COMMIT}
    - build_target=ci

- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: drone
  when:
    status:
    - success
    - failure
